# Create your pod in this case we're using httpd
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    run: httpd
spec:
  containers:
  - image: httpd
    name: httpd
    ports:
    - containerPort: 80
      protocol: TCP
---
# Create your service
apiVersion: v1
kind: Service
metadata:
  labels:
    run: httpd
  name: httpd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: httpd
---
# Create the rule that makes the ingress come to life. A note, the get ingress rule can take some time to update to show its working
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpd
spec:
  rules:
  - host: httpd.192.168.99.100.nip.io
    http:
      paths:
      - backend:
          serviceName: httpd
          servicePort: 80